config/routes.rb
Mountains::Application.routes.draw do
root :to => 'mountains#index'

  get '/mountains' => 'mountains#index'
  post '/mountains' => 'mountains#create'
  get '/mountains/new' => 'mountains#new'

  get '/mountains/:id' => 'mountains#show', :as => 'mountain'
  post'/mountains/:id/delete' => 'mountains#destroy', :as => 'mountain_delete'
  get '/mountains/:id/edit' => 'mountains#edit', :as => 'mountain_edit'
  post '/mountains/:id' => 'mountains#update'

end

app/models/mountain.rb
class Mountain < ActiveRecord::Base
attr_accessible :name, :image, :country, :height

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mountains_controller.rb
class MountainsController < ApplicationController
  def index
      @mountains = Mountain.all
  end

  def new
  end

  def create
    Mountain.create(params[:mountain])
    redirect_to(mountains_path)
    # raise params.inspect

  end

def show
  @mountain = Mountain.find(params[:id])

end


def destroy
  mountain = Mountain.find(params[:id])
  mountain.delete
  redirect_to(mountains_path)
end

def edit
  @mountain = Mountain.find(params[:id])
end

def update
  mountain = Mountain.find(params[:id])
  mountain.update_attributes(params[:mountain])
  redirect_to(mountains_path)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mountains</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="mainwilly">
<nav>
<ul><li><%= link_to('Mountains', mountains_path) %></li>
<li><%= link_to('Upload a Mountain', mountains_new_path) %></li>
</ul>
</nav>


<div class="hero-unit">
<%= yield %>
</div>

<section>
  <footer>
    This is my footer | 2013 </footer>
</section>


</div>

</body>
</html>

app/views/mountains/edit.html.erb
<div class="form-unit">
  <form method='post' action='<%= mountain_path(@mountain.id) %> '>
    <input value=' <%= @mountain.name %>' type='text' name='mountain[name]'>
    <input value=' <%= @mountain.image %>' type='text' name='mountain[image]'>
    <input value=' <%= @mountain.country %>' type='text' name='mountain[country]'>
    <input value=' <%= @mountain.height %>' type='text' name='mountain[height]'>
    <button class="btn btn-success">Update</button>
</form>
</div>

app/views/mountains/index.html.erb
<% @mountains.each do |mountain| %>

<section>
<p><button2><%= link_to(mountain.name, mountain_path(mountain.id)) %></button2><br>

 has <%= pluralize(mountain.height, 'metre') %></p>

<%= link_to('Edit Mountain', mountain_edit_path(mountain.id),:class => 'btn btn-success') %>

  <%= button_to( 'Delete Mountain', mountain_delete_path(mountain.id),:class => 'btn btn-danger') %>


</section>



<% end %>

app/views/mountains/new.html.erb
<div class="form-unit">
  <form method="post" action="/mountains">
    <input type="text" name="mountain[name]" placeholder="Mountain Name" autofocus>
    <input type="text" name="mountain[image]" placeholder="Paste Mountain Image URL">
    <input type="text" name="mountain[country" placeholder="Mountain Country">
    <input type="text" name="mountain[height]" placeholder="Mountain Height in Metres">
    <br/>
    <button>Mountain me!</button>
</form>
</div>

app/views/mountains/show.html.erb
<h1>Introducing:</h1><br/>
<%= image_tag(@mountain.image)   %>
<h2><%= @mountain.name %></h1>
<p>This mountain is <%= @mountain.height %> metres.</p>
<p>Located in <%= @mountain.country %>.</p>